# Generated by Django 3.2.4 on 2021-06-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'verbose_name': 'userProfileInfo', 'verbose_name_plural': 'userProfileInfos'},
        ),
    ]
